- name: Setup desktop environment and user apps
  hosts: localhost
  tasks:
#    - name: Install Flameshot (screenshot tool)
#      community.general.dnf:
#        name: flameshot
#        state: latest

#    # Gnome Shell Extension: Clipboard History (https://extensions.gnome.org/extension/4839/clipboard-history/)
#    - name: "Gnome Shell Extension: Clipboard History"
#      become: yes
#      ansible.builtin.command:
#        cmd: gnome-extensions enable clipboard-history@alexsaveau.dev
#    # Gnome Shell Extension: No overview at start-up (https://extensions.gnome.org/extension/4099/no-overview/)
#    - name: "Gnome Shell Extension: No overview at start-up"
#      become: yes
#      ansible.builtin.command:
#        cmd: gnome-extensions enable no-overview@fthx

# TODO: install OBS
# TODO: install Inkscape
# TODO: install image viewer
# TODO: install image editor
# TODO: install video player (mpv?)