- name: Setup development tools
  hosts: localhost
  tasks:
    - name: Install packages for development
      become: yes
      ansible.builtin.dnf:
        name:
          - java-latest-openjdk-devel
          - nodejs
          - python
        state: latest
    - name: Install rustup
      become: yes
      ansible.builtin.command:
        cmd: curl -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Install jetbrains-toolbox
      become: yes
      ansible.builtin.command:
        cmd: curl -fsLS "https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.1.1.18388.tar.gz" | tar xvz -C "/opt" --strip-components 1
        creates: "/opt/jetbrains-toolbox"
