- name: Setup desktop environment and user apps
  hosts: localhost
  tasks:
    # Set common Gnome settings 
    # Dump with: dconf dump /
    - block:
      # dconf dependencies
      - name: "dconf plugin dependency: python3"
        become: yes
        ansible.builtin.dnf:
          name:
            - python3
            - python3-pip
          state: present
      - name: "dconf plugin dependency: psutil"
        ansible.builtin.pip:
          name: psutil

      # dconf settings
      - community.general.dconf:
          key: /gnome/desktop/background/picture-uri
          value: "'file:///home/sandro/.config/background'"
      - community.general.dconf:
          key: /gnome/desktop/background/picture-uri-dark
          value: "'file:///home/sandro/.config/background'"
      - community.general.dconf:
          key: /org/gnome/desktop/input-sources/sources
          value: "[('xkb', 'us+intl'), ('xkb', 'pt')]"
      - community.general.dconf:
          key: /org/gnome/desktop/interface/color-scheme
          value: "'prefer-dark'"
      - community.general.dconf:
          key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
          value: "true"
      - community.general.dconf:
          key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
          value: "uint32 2700"
      - community.general.dconf:
          key: /org/gnome/desktop/remote-desktop/rdp/enable
          value: "true"
      - community.general.dconf:
          key: /org/gnome/desktop/remote-desktop/rdp/view-only
          value: "false"

#    - name: Install Flameshot (screenshot tool)
#      community.general.dnf:
#        name: flameshot
#        state: latest

#    # Gnome Shell Extension: Clipboard History (https://extensions.gnome.org/extension/4839/clipboard-history/)
#    - name: "Gnome Shell Extension: Clipboard History"
#      become: yes
#      ansible.builtin.command:
#        cmd: gnome-extensions enable clipboard-history@alexsaveau.dev
#    # Gnome Shell Extension: No overview at start-up (https://extensions.gnome.org/extension/4099/no-overview/)
#    - name: "Gnome Shell Extension: No overview at start-up"
#      become: yes
#      ansible.builtin.command:
#        cmd: gnome-extensions enable no-overview@fthx

# TODO: install OBS
# TODO: install Inkscape
# TODO: install image viewer
# TODO: install image editor
# TODO: install video player (mpv?)
