- name: Setup QoL
  hosts: localhost
  tasks:
    - name: Install QoL tools
      become: yes
      ansible.builtin.dnf:
        name:
          - bat        # `cat` alternative
          - difftastic # `diff` alternative
          - eza        # `ls` alternative
#          - fd         # `find` alternative
          - fzf        # fuzzy file search
          - hexyl      # hex viewer
          - jql        # JSON query
          - neovim
#          - oha        # HTTP load generator
          - ripgrep    # `grep` alternative
          - tealdeer   # tldr of man pages
          - zoxide     # `cd` alternative
        state: latest
