- name: Setup CLI
  hosts: localhost
  tasks:
    - name: Install Zsh
      become: yes
      ansible.builtin.dnf:
        name: zsh
        state: latest
    - name: Set Zsh as default shell
      become: yes
      ansible.builtin.user:
        name: "{{ansible_user_id}}"
        shell: "/usr/bin/zsh"
