- name: Setup base
  hosts: localhost
  tasks:
#    - name: "Install font: Meslo (Nerd Font variant)"
#      kewlfft.aur.aur:
#        name: ttf-meslo-nerd
#        state: latest

    # setup chezmoi
    - name: Install chezmoi
      become: yes
      ansible.builtin.dnf:
        name: "https://github.com/twpayne/chezmoi/releases/download/v2.42.2/chezmoi-2.42.2-x86_64.rpm"
        state: present
    - name: Init chezmoi
      ansible.builtin.command:
        cmd: chezmoi init --apply https://github.com/SandroHc/sandro-dotfiles.git
        creates: "$HOME/.local/share/chezmoi"
